version: '3.6'

services:
  node-app:
    build:
      context: ./node
    container_name: node
    ports: 
      - "3000:3000"
    networks:
      - nodengx
    depends_on:
      - mysql
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
  
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - nodengx
    depends_on:
      - node-app

  mysql:
    image: mysql:5.7
    restart: always
    tty: true
    container_name: db
    command: --innodb-use-native-aio=0
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - nodengx
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    ports:
      - "3306:3306"
    expose:
      - 3306

networks:
  nodengx:
    driver: bridge
